---

- stat:
    path: "/etc/dd-agent"
  register: dd_agent

- stat:
    path: "/etc/datadog-agent"
  register: datadog_agent

- name: Publish The Beanstalkd Check (dd-agent)
  copy:
    src: "checks.d/beanstalkd.py"
    dest: "/etc/dd-agent/checks.d"
    owner: "{{ datadog_user }}"
    group: "{{ datadog_group }}"
    mode: 0644
  when: dd_agent.stat.exists and dd_agent.stat.isdir

- name: Publish The Beanstalkd Check (datadog-agent)
  copy:
    src: "checks.d/beanstalkd.py"
    dest: "/etc/datadog-agent/checks.d"
    owner: "{{ datadog_user }}"
    group: "{{ datadog_group }}"
    mode: 0644
  when: datadog_agent.stat.exists and datadog_agent.stat.isdir

- name: Install The Beanstalkc Python Client
  command: /opt/datadog-agent/embedded/bin/pip install beanstalkc

#- name: Gather Existing Check List
#  find:
#    paths="/etc/dd-agent/conf.d"
#    patterns="*.yaml,*.yml"
#  register: dd_conf
#  when: datadog_purge_existing_checks

#- name: Purge Any Existing Checks
#  file:
#    path="{{ item.path }}"
#    state="absent"
#  with_items: "{{ dd_conf.files }}"
#  when: datadog_purge_existing_checks

- name: Restart DD Agent
  command: /bin/true
  notify: restart datadog-agent
